export const ncbStatusMap: Record<string, string> = {
  '01': 'Normal - No overdue payments over 90 days',
  '010': 'Normal - No overdue payments over 90 days',
  '11': 'Account Closed - Debt fully paid or restructured debt fully paid',
  '011': 'Account Closed - Debt fully paid or restructured debt fully paid',
  '12': 'Debt Moratorium - Based on member policy',
  '012': 'Debt Moratorium - Based on member policy',
  '13': 'Debt Moratorium - Based on government policy',
  '013': 'Debt Moratorium - Based on government policy',
  '14': 'Farmer Debt Moratorium - Based on government policy',
  '014': 'Farmer Debt Moratorium - Based on government policy',
  '20': 'Overdue over 90 days - Classified as Non-Performing Loan (NPL)',
  '020': 'Overdue over 90 days - Classified as Non-Performing Loan (NPL)',
  '21': 'Overdue over 90 days - Affected by abnormal situations',
  '021': 'Overdue over 90 days - Affected by abnormal situations',
  '30': 'In Legal Process',
  '030': 'In Legal Process',
  '31': 'Paying debt according to court judgment',
  '031': 'Paying debt according to court judgment',
  '32': 'Case dismissed due to statute of limitations or other reasons',
  '032': 'Case dismissed due to statute of limitations or other reasons',
  '33': 'Account closed due to bad debt write-off',
  '033': 'Account closed due to bad debt write-off',
  '40': 'Paying credit to close account - Account restricted',
  '040': 'Paying credit to close account - Account restricted',
  '41': 'Under investigation - Fraud or dispute',
  '041': 'Under investigation - Fraud or dispute',
  '42': 'Debt sold/transferred - Overdue over 90 days',
  '042': 'Debt sold/transferred - Overdue over 90 days',
  '43': 'Debt sold/transferred and fully paid',
  '043': 'Debt sold/transferred and fully paid',
  '44': 'Debt sold/transferred - Normal status',
  '044': 'Debt sold/transferred - Normal status',
};

export function getNcbDescription(code: string): string {
  return ncbStatusMap[code] || 'Status not found';
}
